# this file is managed by dry-rb/devtools project

name: sync_configs

on:
  repository_dispatch:
  push:
    branches:
      - "master"

jobs:
  sync-configs:
    runs-on: ubuntu-latest
    if: (github.event_name == 'repository_dispatch' && github.event.action == 'sync_configs') || github.event_name != 'repository_dispatch'
    env:
      PATH: "tmp/devtools/bin:$PATH"
      GITHUB_LOGIN: dry-bot
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout ${{github.repo}}
        uses: actions/checkout@v2
      - name: Checkout devtools
        uses: actions/checkout@v2
        with:
          repository: dry-rb/devtools
          path: tmp/devtools
      - name: Set up Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.6
      - name: Install latest bundler
        run: |
          gem install bundler
          bundle config set without 'test tools benchmarks docs'
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Symlink ossy
        run: bundle binstubs ossy
      - name: Compile file templates
        run: compile-templates
      - name: Update workflow files from devtools
        run: sync-workflows
      - name: Update configuration files from devtools
        run: sync-shared-files
      - name: Commit changes
        run: |
          rm bin/ossy
          git config --local user.email "dry-bot@dry-rb.org"
          git config --local user.name "dry-bot"
          git add -A
          git commit -m "[devtools] sync configs" || echo "nothing changed"
          git pull --rebase origin master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
